---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rent
  labels:
    app: rent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rent
  template:
    metadata:
      labels:
        app: rent
    spec:
      containers:
        - name: rent
          image: 879772956301.dkr.ecr.ap-northeast-2.amazonaws.com/user01-rent:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: rent
  labels:
    app: rent
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: rent