server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Order
          uri: http://localhost:8081
          predicates:
            - Path=/order/** 
        - id: Stock
          uri: http://localhost:8082
          predicates:
            - Path=/stock/** 
        - id: Payment
          uri: http://localhost:8083
          predicates:
            - Path=/payment/** 
        - id: Dashboard
          uri: http://localhost:8084
          predicates:
            - Path= /dashboard/**
        - id: Rent
          uri: http://localhost:8085
          predicates:
            - Path=/rent/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/order/** 
        - id: stock
          uri: http://stock:8080
          predicates:
            - Path=/stock/** 
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/payment/** 
        - id: dashboard
          uri: http://dashboard:8080
          predicates:
            - Path= /dashboard/**
        - id: rent
          uri: http://rent:8080
          predicates:
            - Path=/rent/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
  
